### ISSUE TITLE
Not saved video share Youtube and displays  error message

### ISSUE THREAD

**Issue by olairmarcos** [iionly/Elgg_1.8_izap_videos#1] opened 2015-05-21 14:49 UTC
Hello,
When I go to the url youtube share: https://youtu.be/8Ove3or9ahA
Not saved and displays the following error message: This URL is not supported.
Version Elgg: 1.9.0
Version Izap_videos: 1.9.5
Thanks for help.

**Comment by iionly** [comment] 2015-05-21 18:06
Currently the adding of Youtube videos works only with youtube.com urls and not with youtu.be urls. If I have a little bit of time to spare I'll try to get it working also with youtu.be urls (in a new release of the Izap Videos plugin then). In the meantime you can simply use youtube.com instead of youtu.be in the url and it should work as the video id is the same.

**Comment by olairmarcos** [comment] 2015-05-22 19:30
To save the video share (youtube) works well. When I delete a video, I have this error msg:
Fatal error: Class 'PDO' not found in home/sitetestcom/public_html/mod/izap_videos/lib/izap_sqlite.php on line 50
Video not deleted. When acess administration panel (utilities > IZAP videos) apears the some error.
Thanks for help

**Comment by iionly** [comment] 2015-05-25 07:10
The pdo_sqlite php extension seems not installed or enabled on your server. This means that your server does not meet the requirements for on-server video support of the iZAP Videos plugin. Do you have enabled the on-server videos options in the plugin settings nevertheless? If yes, try it again with on-server videos support disabled. Does it work then?

**Comment by olairmarcos** [comment] 2015-05-26 13:27
Thanks for the answer. It may be that (PDO_sqlite) is disabled on the server. I'm currently using izap_video only to share Youtube videos in the community. The function to load videos on the site is disabled. Thanks

**Comment by iionly** [comment] 2015-05-27 11:11
With the on-server video option disabled you shouldn't get an error on the plugin settings page. Can you confirm this?

For deletion of videos to work without the pdo_sqlite extension being available a fix in lib/izap_videos.php seems necessary within the delete method:

``` php
public function delete() {
        // in case of an uploaded video make sure it's also deleted from queue and trash
        // with related media if it still remained there
        if ($this->videotype == 'uploaded') {
            $queue_object = new izapQueue();
            $queue_object->delete_from_trash($this->guid, true);
            $queue_object->delete($this->guid, true);
        }

        $imagesrc = $this->imagesrc;
        $filesrc = $this->videofile;
        $ofilesrc = $this->orignalfile;
        //delete entity from elgg db and corresponding files if exist
        $this->setFilename($imagesrc);
        $image_file = $this->getFilenameOnFilestore();
        file_exists($image_file) && @unlink($image_file);

        $this->setFilename($filesrc);
        $video_file = $this->getFilenameOnFilestore();
        file_exists($video_file) && @unlink($video_file);

        $this->setFilename($ofilesrc);
        $orignal_file = $this->getFilenameOnFilestore();
        file_exists($orignal_file) && @unlink($orignal_file);

        return parent::delete();
    }
```

Would it be possible for you to test this change and tell me if it's working for you?

**Comment by olairmarcos** [comment] 2015-05-28 04:04
Hello,
I managed to solve the problem with pdo_sqlite extension, added lines in the php.ini file and is working properly.

extension=pdo.so
extension=pdo_mysql.so
extension=pdo_sqlite.so
extension=mysql.so

I managed to delete the video after changing the /lib/izap_videos.php file. Now I can no longer load any new video on the site, it appears that it is necessary to implement the Youtube developer key to share videos on the site. I'm not sure.
At the moment I can not share youtube videos on the site, or copying the video url and also the shortened url not working.
When trying to share a video appears the error msg: Can not get the video from the site. Site is not responding.

Thanks for help.

**Comment by iionly** [comment] 2015-05-28 12:16
You're mixing different issues here.

The short urls (youtu.be) don't work - yet. I've implemented it in the meantime and it will work in the next release.

Generally, you need an API key to be able to add youtube videos now. That's because Youtube (Google) turned of the old API and the new API works only when authenticated with an API key. Just follow the link on the API key tab on the iZAP Videos settings page for instructions on how to obtain a key.

The pdo_sqlite extension should only be necessary for on-server videos. On deletion of videos the current version of iZAP Videos tries to clean data only existing for uploaded videos without checking if the video entry to be deleted is even an on-server video. With the modified code I posted this problem shouldn't occur anymore and then the pdo_sqlite extension shouldn't be necessary anymore if the on-server video option isn't enabled. If you would be able to tell me if this works for you - without the modification of php.ini - it would help me to know if it's working as intended. The next release of iZAP Videos should contain this fix also and the sooner I know it's working the sooner I can make the release.

**Comment by olairmarcos** [comment] 2015-05-28 14:58
Hello, IIonly
I understand your explanation.
Now I can not share any video in Elgg site. While trying to save the Youtube video URL appears the error msg: Can not get the video from the site. Site is not responding.
So I can not test that it is working properly.

**Comment by iionly** [comment] 2015-05-28 18:40
Fixed with releases 1.X.6 (X corresponding to the Elgg version it's compatible with). In your case using Elgg 1.9 use iZAP Videos 1.9.6.

You can now enter the Google API key even with on-server videos option disabled. But the API key is mandatory for being able to add Youtube videos. Adding videos using the "youtu.be" urls now works, too.

**Closed as completed by iionly** 2015-05-28 18:40 UTC

**Comment by olairmarcos** [comment] 2015-05-29 04:39
Hello iionly. I installed the new version (1.9.6) izap_videos and did several tests to share Youtube videos on Elgg site. Everything works perfectly.
I'm PDO_SQLITE enabled on the server. There appeared no error message now.
I added the api-key and everything works properly.
I have done videos load test to the site. I will not use this feature to save the video files on the site.
My congratulations for the wonderful work.
Thank you very much.
